version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # have rust's dependencies check
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly